-- ================================================================================
--   mysql SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   mysql
--   Generated at:      Tue Nov 29 19:26:50 2005
--   Input Files:       db.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Nov 29 19:26:49 2005
--     Input Files:       db.dia

-- drop constraint priorytet for mysql
-- drop constraint kategoria for mysql
-- drop constraint wlasciciel for mysql


-- Generated Permissions Drops
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Nov 29 19:26:49 2005
--     Input Files:       db.dia




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Nov 29 19:26:49 2005
--     Input Files:       db.dia



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Nov 29 19:26:49 2005
--     Input Files:       db.dia

 drop table if exists zadania ;
 drop table if exists pozycje_slownikow ;
 drop table if exists uzytkownicy ;


-- Generated SQL Schema
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Nov 29 19:26:49 2005
--     Input Files:       db.dia


-- zadania
create table zadania (
  zad_id                    int not null auto_increment,
  zad_tytul                 varchar(255),
  zad_opis                  text,
  zad_postep                int,	-- postep lub status wyrazany w procentach
  zad_data_rozpoczecia      datetime,
  zad_data_zakonczenia      datetime,
  zad_powiadomienie         int,	-- narazie tylko jest lub nie ma
  zad_psl_pro_id            int not null,
  zad_psl_kat_id            int not null,
  zad_uzk_id                int not null,
  constraint pk_Zadania primary key (zad_id)
) ;

-- pozycje_slownikow
create table pozycje_slownikow (
  psl_id                    int not null auto_increment,
  psl_typ                   varchar(3),	-- typ slownika
  psl_kod                   varchar(3),	-- kod pozycji slownika
  psl_nazwa                 varchar(255),
  psl_wartosc               int,	-- przechowywana wartosc
  constraint pk_Pozycje_slownikow primary key (psl_id)
) ;

-- uzytkownicy
create table uzytkownicy (
  uzk_id                    int not null auto_increment,
  uzk_login                 varchar(32),
  uzk_haslo                 varchar(32),	-- MD5
  uzk_email                 varchar(255),
  constraint pk_Uzytkownicy primary key (uzk_id)
) ;





-- Generated SQL Views
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Nov 29 19:26:49 2005
--     Input Files:       db.dia




-- Generated Permissions
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Nov 29 19:26:49 2005
--     Input Files:       db.dia



-- Generated SQL Insert statements
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Nov 29 19:26:49 2005
--     Input Files:       db.dia



-- Generated SQL Constraints
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Nov 29 19:26:49 2005
--     Input Files:       db.dia

-- alter table zadania add constraint priorytet
--  foreign key (zad_psl_pro_id) references pozycje_slownikow (psl_id) ;
-- alter table zadania add constraint kategoria
--  foreign key (zad_psl_kat_id) references pozycje_slownikow (psl_id) ;
-- alter table zadania add constraint wlasciciel
--  foreign key (zad_uzk_id) references uzytkownicy (uzk_id) ;

